site_name: ROMI Documentation
site_description: Technical documentation of the Robotics for Micro-farms project
site_author: ROMI Team
site_url: https://docs.romi-project.eu/
copyright: 'CC Attribution-NonCommercial-ShareAlike 4.0 International'


# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - 'Farmers Dashboard':
      - 'Introduction': 'Farmers Dashboard/index.md'
      - 'Carrier Module':
          - 'Introduction': 'Farmers Dashboard/bot.md'
          - 'Structure': 'Farmers Dashboard/structure.md'
          - 'Motion System': 'Farmers Dashboard/motion.md'
          - 'Electronics': 'Farmers Dashboard/electronics.md'
          - 'Power': 'Farmers Dashboard/power.md'
      - 'Charging Station': 'Farmers Dashboard/station.md'
      - 'Camera Module': 'Farmers Dashboard/camera.md'
      - 'How to build the cablebot':
          - 'Get the pieces': 'Farmers Dashboard/building.md'
          - 'Assembly instructions': 'Farmers Dashboard/assembly.md'
          - 'Install the software': 'Farmers Dashboard/install.md'
      - 'How to use the cablebot': 'Farmers Dashboard/use.md'
      - 'Crops Insights Pipeline': 'Farmers Dashboard/pipeline.md'
      - 'Farmers Dashboard App': 'Farmers Dashboard/app.md'
      - 'Farmers Dashboard/legacy.md'
  - 'Rover':
      - 'Overview': 'Rover/index.md'
      - 'User Manual': 'Rover/manual.md'
      - 'Configuration': 'Rover/configuration.md'
      - 'Hardware': 'Rover/hardware.md'
      - 'Software': 'Rover/software.md'
      - 'Rover/librcom.md'
  - 'Plant Phenotyping':
      - 'Home': 'plant_imager/index.md'
      - 'Explanations':
        - 'Home': 'plant_imager/explanations/index.md'
        - 'General design': 'plant_imager/explanations/general_design.md'
        - 'Strengths & limitations': 'plant_imager/explanations/strengths_limits.md'
        - 'Geometric workflow': 'plant_imager/explanations/geometric_workflow.md'
        - 'Machine-learning workflow': 'plant_imager/explanations/ml_workflow.md'
        - 'Mask': 'plant_imager/explanations/task_masks.md'
        - 'Image segmentation': 'plant_imager/explanations/task_segmentation2d.md'
      - 'Modules':
        - 'Plant 3D Explorer':
          - 'Home': 'plant-3d-explorer/index.md'
          - 'Guide': 'plant-3d-explorer/guide.md'
      - 'Plant Imager v2':
          - 'Home': 'plant_imager/build_v2/index.md'
          - 'Aluminium frame': 'plant_imager/build_v2/alu_frame.md'
          - 'CNC frame': 'plant_imager/build_v2/cnc_frame.md'
          - 'CNC electronics': 'plant_imager/build_v2/cnc_electronics.md'
          - 'CNC communication': 'plant_imager/build_v2/cnc_communication.md'
          - 'CNC calibration': 'plant_imager/build_v2/cnc_calibration.md'
          - 'Gimbal assembly': 'plant_imager/build_v2/gimbal_setup.md'
          - 'Gimbal communication': 'plant_imager/build_v2/gimbal_communication.md'
          - 'PiCamera setup': 'plant_imager/build_v2/picamera_setup.md'
          - 'Troubleshooting': 'plant_imager/build_v2/troubleshooting.md'
      - 'Plant Imager v3':
          - 'Home': 'plant_imager/build_v3/index.md'
          - 'Aluminium frame': 'plant_imager/build_v3/alu_frame.md'
          - 'CNC frame': 'plant_imager/build_v3/cnc_frame.md'
          - 'Frame & CNC': 'plant_imager/build_v3/frame_cnc.md'
          - 'Enclosure': 'plant_imager/build_v3/enclosure.md'
          - 'CNC electronics': 'plant_imager/build_v3/cnc_electronics.md'
          - 'Flashing Oquam': 'plant_imager/build_v3/flashing_oquam.md'
          - 'CNC communication': 'plant_imager/build_v3/cnc_communication.md'
          - 'Pan Arm': 'plant_imager/build_v3/pan_arm.md'
          - 'CNC & Pan Arm': 'plant_imager/build_v3/cnc_arm.md'
          - 'Manual Gimball': 'plant_imager/build_v3/manual_gimbal.md'
          - 'Pan electronics': 'plant_imager/build_v3/pan_electronics.md'
          - 'PiCamera': 'plant_imager/build_v3/picamera.md'
          - 'Communication overview': 'plant_imager/build_v3/comm_overview.md'
          - 'Flashing RPi OS': 'plant_imager/build_v3/flash_rpi_os.md'
          - 'PiCamera OS': 'plant_imager/build_v3/picamera_soft.md'
          - 'Main controller': 'plant_imager/build_v3/plantimager_controller.md'
          - 'Registry setup': 'plant_imager/build_v3/registry_setup.md'
          - 'Complete BOMs': 'plant_imager/build_v3/boms.md'
          - 'Resources': 'plant_imager/build_v3/resources.md'
      - 'Software setup':
          - 'Home': 'plant_imager/install/index.md'
          - 'Python environments': 'plant_imager/install/create_env.md'
          - 'Database setup': 'plant_imager/install/plantdb_setup.md'
          - 'Plant Imager': 'plant_imager/install/plant_imager_setup.md'
          - 'Virtual Plant Scanner': 'plant_imager/install/virtual_plant_setup.md'
          - 'Plant reconstruction': 'plant_imager/install/plant_reconstruction_setup.md'
          - 'Plant 3D Explorer': 'plant_imager/install/plant3dexplorer_setup.md'
      - 'Tutorials':
          - 'Home': 'plant_imager/tutorials/index.md'
          - 'CLI basics': 'plant_imager/tutorials/basics.md'
          - 'Plant Imager': 'plant_imager/tutorials/hardware_scan.md'
          - 'Intrinsic calibration': 'plant_imager/tutorials/intrinsic_calibration.md'
          - 'Extrinsic calibration': 'plant_imager/tutorials/extrinsic_calibration.md'
          - 'Multiple scans': 'plant_imager/tutorials/multi_scan.md'
          - 'Virtual world': 'plant_imager/tutorials/virtual_plant_imager_single_dataset.md'
          - 'Virtual plant images' : plant_imager/tutorials/virtual_plant_generate_analyze_visualize.md
          - 'Training data for ML': 'plant_imager/tutorials/virtual_plant_imager_large_dataset.md'
          - 'Reconstruct 3D data': 'plant_imager/tutorials/reconstruct_scan.md'
          - 'Explore your data': 'plant_imager/tutorials/plant-3d-explorer.md'
          - 'SM-DTW with simulated data': 'plant_imager/tutorials/tutorial_sm-dtw_simulatephyllotaxis.md'
          - 'Robustness evaluation': 'plant_imager/tutorials/robustness_evaluation.md'
      - 'How-to':
          - 'Home': 'plant_imager/how_to/index.md'
          - 'Colmap': 'assets/notebooks/HowTo -Colmap- From RGB images to camera poses.ipynb'
          - 'Undistorted': 'assets/notebooks/HowTo -Undistorted- Undistort RGB images using camera model.ipynb'
          - 'Masks': 'assets/notebooks/HowTo -Masks- From RGB images to masks.ipynb'
          - 'Voxels': 'assets/notebooks/HowTo -Voxels- From mask images and camera coordinates to volume.ipynb'
          - 'PointCloud': 'assets/notebooks/HowTo -PointCloud- From carved volume to point cloud.ipynb'
          - 'TriangleMesh': 'assets/notebooks/HowTo -TriangleMesh- From point cloud to triangular mesh.ipynb'
          - 'CurveSkeleton': 'assets/notebooks/HowTo -CurveSkeleton- From triangular mesh to curved skeleton.ipynb'
          - 'TreeGraph': 'assets/notebooks/HowTo -TreeGraph- From curved skeleton to tree graph.ipynb'
          - 'AnglesAndInternodes': 'assets/notebooks/HowTo -AnglesAndInternodes- Extract fruits angles and internodes distance from a tree graph.ipynb'
      - 'Specifications':
          - 'Home': 'plant_imager/specifications/index.md'
          - 'Data': 'plant_imager/specifications/data.md'
          - 'Hardware': 'plant_imager/specifications/hardware.md'
          - 'Virtual Plant Imager': 'plant_imager/specifications/virtual-plant-imager.md'
          - 'Metadata':
              - 'Home': 'plant_imager/metadata/index.md'
              - 'Biological metadata': 'plant_imager/metadata/biological_metadata.md'
              - 'Hardware metadata': 'plant_imager/metadata/hardware_metadata.md'
              - 'Software metadata': 'plant_imager/metadata/software_metadata.md'
              - 'Tasks metadata': 'plant_imager/metadata/tasks_metadata.md'
          - 'Luigi': 'plant_imager/specifications/luigi.md'
          - 'Tasks':
              - 'Home': 'plant_imager/specifications/tasks/index.md'
              - 'Files tasks': 'plant_imager/specifications/tasks/file_tasks.md'
              - 'Acquisition tasks': 'plant_imager/specifications/tasks/acquisition_tasks.md'
              - 'Reconstruction tasks': 'plant_imager/specifications/tasks/reconstruction_tasks.md'
              - 'Defining ground truth': 'plant_imager/specifications/tasks/ground_truth_tasks.md'
              - 'Evaluation tasks': 'plant_imager/specifications/tasks/evaluation_tasks.md'
          - 'Pipelines': 'plant_imager/specifications/pipelines.md'
          - 'Configuration files': 'plant_imager/specifications/configuration_files.md'
      - 'Developer':
          - 'Home': 'plant_imager/developer/index.md'
          - 'Pipelines repeatability': 'plant_imager/developer/pipeline_repeatability.md'
          - 'User case scenarios': 'plant_imager/developer/user_case_scenarios.md'
          - 'Git Workflow': 'plant_imager/developer/git_workflow.md'
          - 'Git Submodules': 'plant_imager/developer/git_submodules_workflow.md'
          - 'Contribute to docs': 'plant_imager/developer/git_docReview.md'
          - 'Make a tutorial': 'plant_imager/developer/tutorial_template.md'
          - 'Conda': 'plant_imager/developer/conda.md'
          - 'COLMAP': 'plant_imager/developer/colmap_cli.md'
          - 'VPI API': 'plant_imager/developer/vpi_reference_api.md'
          - 'How-to':
              - 'Home': 'plant_imager/developer/how_to/index.md'
              - 'Import external resources': 'plant_imager/developer/how_to/import_files.md'
              - 'Create a new task': 'plant_imager/developer/how_to/create_new_task.md'
              - 'Create a new evaluation task': 'plant_imager/developer/how_to/create_new_evaluation_task.md'
          - 'Docker':
              - 'Home': 'plant_imager/docker/index.md'
              - 'Database': 'plant_imager/docker/plantdb_docker.md'
              - 'Plant Imager': 'plant_imager/docker/plantimager_docker.md'
              - 'Virtual Plant Imager': 'plant_imager/docker/virtualplantimager_docker.md'
              - 'Colmap': 'plant_imager/docker/colmap.md'
              - 'Plant 3D Vision': 'plant_imager/docker/plant-3d-vision_docker.md'
              - 'Plant 3D Explorer': 'plant_imager/docker/plant3dexplorer_docker.md'
              - 'Docker compose': 'plant_imager/docker/docker_compose.md'
  - Training:
      - 'Home': training/index.md
      - 'LPy': training/lpy.md
      - 'IPPN Angers 2023': training/ippn_2023.md
  - glossary.md

theme:
  name: 'material'
  font:
    text: Nunito Sans
    code: Ubuntu Mono
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  features:
    - navigation.tabs
    - content.code.copy

extra:
  homepage: https://romi-project.eu/
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/ROMI_EU_PROJECT'
    - icon: fontawesome/brands/facebook
      link: 'https://www.facebook.com/ROMIEUProject'
    - icon: fontawesome/brands/github
      link: 'https://github.com/romi/'
  project: 'The ROMI project has received funding from the European Communityâ€™s H2020 Programme under Grant Agreement No. 773875.'
  footer_logo: '/assets/images/eu-flag.png'
  repo_name: romi-robots-docs
  repo_url: https://github.com/romi/romi-robots-docs
  disqus: romi

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: Link

plugins:
  - search
  - gitsnippet
#  - markdown-exec
  - mermaid2:
      version: 10.2.3

extra_css:
  - assets/css/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'
